# Generated by Django 3.1.4 on 2020-12-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('contents', models.TextField()),
                ('inventory', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vtol.item')),
            ],
        ),
    ]
